language: java
jdk: 
- oraclejdk8

services:
- mysql
- docker

before_install: 
- mysql -e 'CREATE DATABASE IF NOT EXISTS inventorydb;'
- mysql -u root < mysql/scripts/load-data.sql
- cd inventory
- chmod +x gradle/wrapper/gradle-wrapper.jar
 
 
script: 
- ./gradlew build
- ./gradlew docker
