language: java
jdk: 
- oraclejdk8

services:
- mysql

before_install: 
- mysql -e 'CREATE DATABASE IF NOT EXISTS inventorydb;'
- cd inventory
- chmod +x gradle/wrapper/gradle-wrapper.jar
 
script: ./gradlew build
